# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20170619_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
